services:
  instube:
    build: .
    container_name: instube_downloader
    ports:
      - "5005:5000"
    volumes:
      - downloads_data:/app/static/downloads
      - ./cookies.txt:/app/cookies.txt
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - default
      - rag_network

volumes:
  downloads_data:

networks:
  default:
  rag_network:
    name: rag-based-ai-teaching-assistant_default
    external: true
