services:
  instube:
    build: .
    container_name: instube_downloader
    ports:
      - "5005:5000"
    volumes:
      - downloads_data:/app/static/downloads
      - ./cookies.txt:/app/cookies.txt
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  downloads_data:
